# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: golang-github-spacemonkeygo-openssl.spec

# add or remove files that should be synced
synced_files:
    - golang-github-spacemonkeygo-openssl.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: openssl
# downstream (Fedora) RPM package name
downstream_package_name: golang-github-spacemonkeygo-openssl

upstream_project_url: https://github.com/lbarcziova/openssl

packit_instances: ["prod", "stg"]
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets: fedora-stable
- job: copr_build
  trigger: commit
  metadata:
    targets: fedora-stable
- job: tests
  trigger: pull_request
  targets: [fedora-stable]
- job: tests
  trigger: commit
  targets: [fedora-stable]